{
    'name': 'Viettelpost Connector',
    'version': '13.0.1.0',
    'summary': 'Connect Odoo Application with Viettel Post',
    'description': """
        The Odoo Viettel Post Connector module is an integrated product between the odoo application and the carrier Viettel Post. 
        The application provides features, which through the api to manipulate directly into the dashboard of Viettel Post.
    """,
    'category': 'Inventory/Delivery Connector',
    'support': 'odoo.tangerine@gmail.com',
    'author': 'Tangerine',
    'license': 'OPL-1',
    'depends': [
        'base',
        'mail',
        'sale',
        'product',
        'stock',
        'contacts',
        'delivery',
        'api_connect_instances'
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/api_connect_instance_data.xml',
        'data/api_endpoints_config_data.xml',
        'data/viettelpost_national_type_data.xml',
        'data/viettelpost_product_type_data.xml',
        'data/viettelpost_waybill_type_data.xml',
        'data/viettelpost_status_data.xml',
        'data/uom_uom_data.xml',
        'data/delivery_carrier_data.xml',
        'data/sequence.xml',
        'data/ir_actions_report.xml',
        'data/res_partner_data.xml',
        'wizard/print_waybill_wizard.xml',
        'wizard/booking_viettelpost_wizard_views.xml',
        'views/assets.xml',
        'views/api_connect_instances_views.xml',
        'views/viettelpost_province_views.xml',
        'views/viettelpost_district_views.xml',
        'views/viettelpost_ward_views.xml',
        'views/viettelpost_office_views.xml',
        'views/viettelpost_service_views.xml',
        'views/viettelpost_store_views.xml',
        'views/viettelpost_national_type_views.xml',
        'views/viettelpost_product_type_views.xml',
        'views/viettelpost_waybill_type_views.xml',
        'views/viettelpost_status_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/stock_picking_views.xml',
        'views/menus.xml'
    ],
    'qweb': ['static/src/xml/button.xml'],
    'images': ['static/description/thumbnail.png'],
    'auto_install': False,
    'application': True
}