from . import viettelpost_address
from . import viettelpost_office
from . import viettelpost_service
from . import viettelpost_store
from . import product_template
from . import delivery_carrier
from . import viettelpost_common_information
from . import res_partner
from . import sale_order
from . import stock_picking
