class ROUTES:
    GetProvinces = '/v2/categories/listProvinceById?provinceId=-1'
    GetDistricts = '/v2/categories/listDistrict?provinceId=-1'
    GetWards = '/v2/categories/listWards?districtId=-1'
    SignIn = '/v2/user/Login'
    SignInOwner = '/v2/user/ownerconnect'
    GetOffices = '/v2/categories/listBuuCucVTP'
    GetServices = '/v2/categories/listService'
    GetExtendServices = '/v2/categories/listServiceExtra?serviceCode={}'
    GetStores = '/v2/user/listInventory'
    SetStore = '/v2/user/registerInventory'
    ComputeFeeAll = '/v2/order/getPriceAll'
    CreateWaybill = '/v2/order/createOrder'
    UpdateWaybill = '/v2/order/UpdateOrder'
    PrintWaybill = '/v2/order/printing-code'
    CheckShipCost = '/v2/order/getPrice'
